### ISSUE TITLE
I am kick 30 seconds after spawn in the map.

### ISSUE THREAD

**Issue by lolesx** [Pro-Swapper/ProSwapper#10]
I am kick 30 seconds after spawn in the map.
Sorry for my english level, i am french

**Comment by lolesx** [comment]
![image](https://user-images.githubusercontent.com/99119541/193565967-e6329671-3910-4029-ae4f-4f3df529276f.png)

**Comment by KyeOnDiscord** [comment]
If you're swapping an emote make sure it's not in your locker wheel

**Comment by lolesx** [comment]
oh sorry it's good
