### ISSUE TITLE
When i launch it closes immediately i have .NET installed and it wont work 

### ISSUE THREAD

**Issue by WI3E** [Pro-Swapper/ProSwapper#11]
I dont know how to fix it from crashing as soon as i open it

**Comment by KyeOnDiscord** [comment]
Try putting Pro Swapper exe in a new folder and turn off any anti viruses

**Comment by Sketchersz** [comment]
I turned off all my anti viruses, move it to a new folder and it still does not open.

**Comment by KyeOnDiscord** [comment]
Could you send your Pro Swapper log here? https://docs.proswapper.xyz/pro-swapper/getting-pro-swapper-logs

**Comment by Nachitox865** [comment]
hello, in my case it lets me open fortnite and it works, but when I enter the game it takes me out in a few seconds.
I do not know if it is understood I am using a translator.

**Comment by KyeOnDiscord** [comment]
> hello, in my case it lets me open fortnite and it works, but when I enter the game it takes me out in a few seconds. I do not know if it is understood I am using a translator.

Make sure you aren't swapping too many items and if you're swapping an emote, take it out of your locker wheel
