### ISSUE TITLE
non-negative number required. parameter'value'

### ISSUE THREAD

**Issue by cesarlevi** [Pro-Swapper/ProSwapper#18]

**Comment by luis2321313** [comment]
me dice que se requiere un numero negativo parámetro de valor

**Comment by luis2321313** [comment]
A non-negative number is required. (parameter 'value')
That tells me when I'm going to convert skins, spikes

**Comment by luis2321313** [comment]
I get when I go to convert skins, spikes in fortnite I get the
mistake this

**Comment by Cirola3ra** [comment]
there's an solution to this problem?

**Comment by KyeOnDiscord** [comment]
The swapper is currently patched, for more info read this message on the discord https://discord.com/channels/703033424541384784/870057538408833034/1052705351344078949
