### ISSUE TITLE
OG Pump 

### ISSUE THREAD

**Issue by hubbigaming** [Pro-Swapper/ProSwapper#2]
When you have Pump to OG Pump ON and oupen your  inventory it shows the icon of the new Pump. I dont know if this is a bug. I just wanted to inform you. Have a nice day/weekend proswapper developers

**Comment by KyeOnDiscord** [comment]
> When you have Pump to OG Pump ON and oupen your inventory it shows the icon of the new Pump. I dont know if this is a bug. I just wanted to inform you. Have a nice day/weekend proswapper developers

I had to remove the `-L` (large) icon for the pump so you wouldn't get kicked, it's a small "bug" but you can live with it :)
