### ISSUE TITLE
Pro Swapper Ch 2 Season 7

### ISSUE THREAD

**Issue by Jaqksoon** [Pro-Swapper/ProSwapper#3]
I tried it out and was only using 1 swap and it was still kicking me out for some reason, any ways I can fix this?

**Comment by KyeOnDiscord** [comment]
> I tried it out and was only using 1 swap and it was still kicking me out for some reason, any ways I can fix this?

Try verifying Fortnite and reswap, if that doesn't work the item may be broken, there isn't anything I can do to fix it as kicking is all on Fortnite's end.

**Comment by Jaqksoon** [comment]
i fixed it, all I did was just cancel the install on the epic games launcher and then go in squads and instaleave

**Comment by KyeOnDiscord** [comment]
> i fixed it, all I did was just cancel the install on the epic games launcher and then go in squads and instaleave

You can close Epic Games Launcher when you go into lobby and that'll cancel verification after closing the game, the squads and leaving method is "unreliable" but if it works for you that's great :)
