### ISSUE TITLE
[LOBBY SWAP] Bad state (invalid window size 17)) (pakchunk0-WindowsClient.pak could not be exported)

### ISSUE THREAD

**Issue by industdev** [Pro-Swapper/ProSwapper#4]
First 4-5 Swap work but then there is this error...

![image](https://user-images.githubusercontent.com/66631504/127772893-c581a6a8-2ab0-4992-82d2-1e73ab5267fa.png)
![image](https://user-images.githubusercontent.com/66631504/127772898-39334dc4-71ad-4914-a918-76915b8e5389.png)
![image](https://user-images.githubusercontent.com/66631504/127772902-9d052b6f-1387-4935-bfdd-6c5d5c977638.png)
Fortnite doesn't crash

Also could we have the legacy lobby swapper window? 
Where you put the cid above and below
(if possible .cid files too :>)

You did an amazing job at making the lobby feature, i can now keep trolling kids, thank you
Kye, i love you, stay safe and take your time

**Comment by KyeOnDiscord** [comment]
![image](https://user-images.githubusercontent.com/36981621/127784879-846b9895-eda1-41b9-959a-8e33a551f625.png)
I've tried to swap more than 5 items and the error does not seem to be happening to me, if you've used another swapper you may have duplicate files (and maybe for pakchunk0), try installing [FModel](https://github.com/iAmAsval/FModel/releases) and see how many pak files are loaded

**Comment by industdev** [comment]
![image](https://user-images.githubusercontent.com/66631504/127839554-ea1c8277-b82c-4b2e-afb0-9e0faef7a771.png)
![image](https://user-images.githubusercontent.com/66631504/127839660-b854cdb5-d338-467b-a1a1-3f7b6951144f.png)
(Tried loading all paks)

**Looks like proswapper corrupts assetregistry.bin**

![image](https://user-images.githubusercontent.com/66631504/127839936-5cacbd48-f112-4c4d-8775-294043aec7ec.png)
**^ Because its corrupted, even fmodel can't visualize it**
![image](https://user-images.githubusercontent.com/66631504/127840078-79678a70-ef5c-42ea-858f-9f134ab48c5a.png)

**Comment by KyeOnDiscord** [comment]
Pro Swapper edits AssetRegistry.bin to Lobby Swap, something may have gone wrong during the compression. Verifying Fortnite is the best way to fix this. If that doesn't work a full reinstall of Fortnite may be required.
